### ISSUE TITLE
[Interactive Map]: Implementation for other games

### ISSUE THREAD

**Issue by ero-qt** [Voxelse/voxelse.github.io#2]
Hi!

I'm hoping to reach you this way about creating something similar to your interactive map for A Short Hike for the game Lil Gator Game. I'm mostly wondering about how you managed to get such a good screenshot of the whole map? What with the fog and everything.

Other than that, we'd obviously love such a map for a game which requires extensive routing such as LGG. If you have any advice on how to perhaps expand on your creation, or how to create something similar, or just how to properly adjust yours to work for our needs, that'd be absolutely brilliant. Thanks.

**Comment by Voxelse** [comment]
Hi.

To get a huge screenshot of the game world you'll need to mod the game.
Basically for ASH I had to adjust the camera, render distance, lod and remove all the things that were in the way like the player, fog, clouds, aurora borealis etc. and then I took a screenshot directly from the game with a really huge resolution so there are enough details to be able to zoom in.

And to adapt my work with your needs, well it depends what you need. If the base of the app is enough you can change the names, images and positions of things, like you already did for an other game if I remember correctly.
Otherwise you'll have to code your own features that suits the new needs for the specific game (like I did for pathing and fishing).
But, to be honest the code I wrote back then is very ugly as it was the first time I did a project like this and wasn't supposed to be reused for other projects so it's very likely going to be a burden to continue working from it.

I'm quite busy lately and with the holidays it won't help but if you can't get something working by the new year, you can come back here (or close the issue otherwise) and I'll see if I can do something.

**Comment by ero-qt** [comment]
Thanks for the response.

I was able to get a high quality map from the developers themselves. Very high quality, in fact: 8192x8192. This actually leads to `DOMException: The source image cannot be decoded.` when the page is loaded. I'm unsure of a way to fix this, so I've just scaled the image down.

I don't imagine I'll reach a satisfying end result trying by myself. Making it easy to adjust for other users would be a noble goal, but I certainly can't do that myself. I'll give it an honest try and keep this issue updated.

**Comment by ero-qt** [comment]
I've published my work-in-progress for now: [just-ero/just-ero.github.io](https://github.com/just-ero/just-ero.github.io).  
The map is at https://just-ero.github.io/lgg/interactive-map.

I'm making use of Sass and JavaScript imports to make adjustments easier for further users.

Current obvious gripes: map starts in the top-left instead of somewhere in the center (setting `left` and `top` CSS attributes mess with the zoom feature), zoom is not smoothed (couldn't get it to work).

I've simplified the pad and zoom code by a huge margin, but I'm afraid that might cause issues with scaling the items later on? I'm not sure.

I want the actual data to be provided as `.json` files once I'm at that point.

**Comment by ero-qt** [comment]
Making this accessible for smaller screens (phones) is also an important step to take.

**Comment by ero-qt** [comment]
I haven't made any progress on this over the holidays (for exactly that reason). However, someone suggested to me to use [`leafletjs`](https://leafletjs.com) for the map. Do you know anything about it? Would it be a good fit?

**Comment by ero-qt** [comment]
Leaflet JS seems to be working very well, as it turns out. I'll have to play with it more to truly understand how any of it works, but the simplest setup works very well out of the box.

I have it set up and working on [just-ero/just-ero.github.io#leaflet-js](https://github.com/just-ero/just-ero.github.io/tree/leaflet-js).

**Comment by ero-qt** [comment]
Yup, LeafletJS is the way to go. Looking absolutely fabulously over on https://just-ero.github.io/map/lgg.
